import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { UserProvider } from '../contexts/userContext';
import Navbar from './components/Navbar';
import Provider from './components/Provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Ceres Tours',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang='en'>
            <body className='bg-background'>
                    <Provider>
                        <UserProvider>
                            {children}
                        </UserProvider>
                    </Provider>
            </body>
        </html>
    );
}